import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
import type { CommunityFile, LoaderName } from '../../shared/types'
import type { MigrationEntry, ModMigrationPlan } from '../../shared/modMigration'
import { scanModDirectory } from './modScan'
import { resolveResourceDirectory, requireResourceVersion } from './resourceDirectory'
import { withGameFolder } from './paths'
import { installVersion, type ProgressEmit } from './versions'
import { setNewInstanceIsolation } from './instances'
import { listLoaderVersions } from './loaders'
import { communityFiles, communityExactFile, cfChannel } from './community'
import { httpFetch } from './httpClient'
import { downloadFile } from './download'
const plans=new Map<string,ModMigrationPlan>(),running=new Set<string>()
const MR='https://api.modrinth.com/v2'
async function post(url:string,body:unknown,headers:Record<string,string>={}){const r=await httpFetch(url,{method:'POST',headers:{'Content-Type':'application/json','User-Agent':'KAMUCL (github.com/kamubaba-i/KAMUCL)',...headers},body:JSON.stringify(body),signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error('社区查询失败 HTTP '+r.status);return r.json() as Promise<any>}
export function compatibleFile(file:CommunityFile,mc:string,loader:string){return !!file.url&&/^https:\/\//.test(file.url)&&/^[a-f0-9]{40}$/i.test(file.sha1||'')&&file.gameVersions.includes(mc)&&file.loaders.includes(loader as LoaderName)&&/\.jar$/i.test(file.fileName)&&path.basename(file.fileName)===file.fileName&&!/[\\/:\0]/.test(file.fileName)}
export async function planModMigration(sourceId:string,folder:string,mcVersion:string,loader:LoaderName):Promise<ModMigrationPlan>{
 requireResourceVersion(sourceId);if(!/^[a-zA-Z0-9._-]{1,80}$/.test(mcVersion)||!['fabric','forge','neoforge','quilt'].includes(loader))throw new Error('请选择有效的游戏版本与加载器')
 const dir=await resolveResourceDirectory(folder,sourceId,'mods')
 const names=(await fs.promises.readdir(dir,{withFileTypes:true}).catch(e=>{if(e.code==='ENOENT')return [];throw e})).filter(e=>e.isFile()&&/\.jar(?:\.disabled)?$/i.test(e.name)).map(e=>e.name)
 if(names.length>500)throw new Error('单次最多迁移500个模组，请先整理模组列表');if(!names.length)throw new Error('当前版本没有可迁移的模组')
 const [scanned,loaders]=await Promise.all([scanModDirectory(dir,true,names),listLoaderVersions(loader,mcVersion)])
 if(!loaders[0])throw new Error(`${loader} 没有适配 ${mcVersion} 的加载器`)
 const entries:MigrationEntry[]=await Promise.all(scanned.map(async i=>({fileName:i.fileName,name:i.name||i.fileName,currentVersion:i.version||'',sha1:i.sha1||crypto.createHash('sha1').update(await fs.promises.readFile(path.join(dir,i.fileName))).digest('hex'),disabled:/\.disabled$/i.test(i.fileName),status:'unavailable',reason:i.error?'文件无法解析，保留为禁用文件':'未匹配社区来源'})))
 let originals:any={},updates:any={},mrError=''
 try{originals=await post(MR+'/version_files',{hashes:entries.map(e=>e.sha1),algorithm:'sha1'});updates=await post(MR+'/version_files/update',{hashes:entries.map(e=>e.sha1),algorithm:'sha1',game_versions:[mcVersion],loaders:[loader]})}catch(e){mrError=String(e)}
 const missing=entries.filter(e=>!originals[e.sha1]),cfIds=new Map<string,string>()
 if(missing.length){const channel=cfChannel();try{const result=await post(channel.base+'/fingerprints',{fingerprints:scanned.filter(i=>missing.some(e=>e.fileName===i.fileName)).map(i=>i.fingerprint).filter(x=>x!=null)},channel.key?{'x-api-key':channel.key}:{});for(const e of missing){const match=result.data?.exactMatches?.find((m:any)=>m.file?.hashes?.some((h:any)=>h.algo===1&&String(h.value).toLowerCase()===e.sha1));if(match)cfIds.set(e.sha1,String(match.file.modId||match.id))}}catch(e){throw new Error('无法完成社区来源识别，请检查网络后重试。'+(mrError||String(e)))}}
 if(mrError)throw new Error('Modrinth 查询失败，请重试：'+mrError)
 const versions=new Map<string,CommunityFile>();let index=0
 await Promise.all(Array.from({length:4},async()=>{while(index<entries.length){const e=entries[index++],v=updates[e.sha1],project=originals[e.sha1]?.project_id;if(project){e.reason='该项目没有适配目标版本与加载器的文件';if(v){const f=v.files?.find((x:any)=>x.primary)||v.files?.[0];if(f){const file:CommunityFile={source:'modrinth',projectId:v.project_id,fileId:v.id,fileName:f.filename,url:f.url,sha1:f.hashes?.sha1,size:f.size,releaseType:v.version_type||'release',version:v.version_number,date:v.date_published,gameVersions:v.game_versions||[],loaders:v.loaders||[],dependencies:v.dependencies?.map((d:any)=>({required:d.dependency_type==='required',projectId:d.project_id,fileId:d.version_id}))};if(compatibleFile(file,mcVersion,loader)){e.target=file;e.status='compatible';versions.set(file.source+':'+file.projectId,file)}}}}else if(cfIds.has(e.sha1)){e.reason='该项目没有适配目标版本与加载器的可下载文件';const list=await communityFiles('curseforge',cfIds.get(e.sha1)!,{mcVersion,loader,kind:'mod'});const file=list.find(f=>compatibleFile(f,mcVersion,loader));if(file){e.target=file;e.status='compatible';versions.set(file.source+':'+file.projectId,file)}}}}))
 const warnings:string[]=[],visited=new Set<string>()
 for(let n=0;n<entries.length;n++){if(entries.length>500)throw new Error('前置依赖超过500项，请检查模组依赖关系');const e=entries[n];if(!e.target||e.disabled)continue;for(const dep of e.target.dependencies||[]){if(!dep.required)continue;const source=e.target.source||'modrinth',key=source+':'+(dep.projectId||'')+':'+(dep.fileId||'');if(visited.has(key))continue;visited.add(key);const existing=versions.get(source+':'+dep.projectId);if(existing){if(entries.filter(x=>x.target?.source===source&&x.target?.projectId===dep.projectId).every(x=>x.disabled))entries.push({fileName:'',name:existing.fileName,currentVersion:'',sha1:'',disabled:false,status:'dependency',target:existing});if(dep.fileId&&existing.fileId!==dep.fileId)warnings.push(`${e.fileName} 需要特定前置版本 ${dep.fileId}，当前目标版本为 ${existing.fileName}，请确认兼容性`);continue}try{const file=dep.fileId?await communityExactFile(source,dep.projectId,dep.fileId):(await communityFiles(source,dep.projectId||'',{mcVersion,loader,kind:'mod'})).find(f=>compatibleFile(f,mcVersion,loader));if(!file||!compatibleFile(file,mcVersion,loader))throw new Error('无兼容可下载版本');versions.set(source+':'+file.projectId,file);entries.push({fileName:'',name:file.fileName,currentVersion:'',sha1:'',disabled:false,status:'dependency',target:file})}catch(err){warnings.push(`${e.fileName||e.name} 的必要前置 ${dep.projectId||dep.fileId||'未知'} 未能匹配：${String(err)}`)}}}
 const plan:ModMigrationPlan={id:crypto.randomUUID(),sourceId,folder,mcVersion,loader,loaderVersion:loaders[0],entries,warnings,createdAt:Date.now()};for(const[id,p]of plans)if(Date.now()-p.createdAt>1800000)plans.delete(id);plans.set(plan.id,structuredClone(plan));return plan
}
export async function validateMigrationSource(plan:ModMigrationPlan,dir:string){const names=(await fs.promises.readdir(dir,{withFileTypes:true})).filter(e=>e.isFile()&&/\.jar(?:\.disabled)?$/i.test(e.name)).map(e=>e.name).sort();const expected=plan.entries.filter(e=>e.fileName).map(e=>e.fileName).sort();if(JSON.stringify(names)!==JSON.stringify(expected))throw new Error('检查后模组列表发生变化，请重新检查');for(const e of plan.entries.filter(e=>e.fileName)){const stat=await fs.promises.lstat(path.join(dir,e.fileName));if(!stat.isFile()||stat.isSymbolicLink()||crypto.createHash('sha1').update(await fs.promises.readFile(path.join(dir,e.fileName))).digest('hex')!==e.sha1)throw new Error('检查后模组文件已变化，请重新检查：'+e.fileName)}}
export async function applyModMigration(id:string,confirmMissing:boolean,emit:ProgressEmit,signal?:AbortSignal){
 const plan=plans.get(id);if(!plan||Date.now()-plan.createdAt>1800000)throw new Error('迁移预览已过期，请重新检查');if((plan.entries.some(e=>e.status==='unavailable')||plan.warnings.length)&&confirmMissing!==true)throw new Error('请先确认未匹配模组与依赖提醒');if(running.has(id))throw new Error('该迁移正在进行');running.add(id)
 let stage='';try{const dir=await resolveResourceDirectory(plan.folder,plan.sourceId,'mods');emit({stage:'download',progress:0,overall:0,text:'正在校验迁移源文件'});
 await validateMigrationSource(plan,dir);signal?.throwIfAborted();stage=await fs.promises.mkdtemp(path.join(plan.folder,'.kamucl-migration-'));let i=0;const used=new Map<string,string>()
 for(const e of plan.entries){signal?.throwIfAborted();const base=e.target?.fileName||e.fileName.replace(/\.disabled$/i,''),name=base+(e.disabled||!e.target?'.disabled':'');const digest=e.target?.sha1||e.sha1;const previous=used.get(name.toLowerCase());if(previous){if(previous!==digest)throw new Error('迁移文件名冲突：'+name);continue}used.set(name.toLowerCase(),digest);const dest=path.join(stage,name);if(e.target)await downloadFile(e.target.url,dest,(d,t)=>emit({stage:'download',progress:t?d/t:0,overall:.65*(i+(t?d/t:0))/plan.entries.length,text:'迁移模组 '+(e.fileName||e.name)}),e.target.sha1,undefined,signal,[],{size:e.target.size});else await fs.promises.copyFile(path.join(dir,e.fileName),dest,fs.constants.COPYFILE_EXCL);i++}
 await validateMigrationSource(plan,dir);signal?.throwIfAborted();const targetId=(plan.sourceId.slice(0,65)+' - '+plan.mcVersion+' - '+plan.id.slice(0,8));requireResourceVersion(targetId);if(fs.existsSync(path.join(plan.folder,'versions',targetId)))throw new Error('目标迁移实例已存在，请重新检查生成新实例')
 await withGameFolder(plan.folder,async()=>{await installVersion(plan.mcVersion,{loader:plan.loader,loaderVersion:plan.loaderVersion,instanceName:targetId},e=>emit({...e,overall:.65+.3*(e.overall??e.progress),text:'准备目标游戏：'+e.text}),signal);setNewInstanceIsolation(targetId,true);const marker=path.join(plan.folder,'versions',targetId,'.installing');await fs.promises.writeFile(marker,'版本迁移尚未完成');signal?.throwIfAborted();const mods=await resolveResourceDirectory(plan.folder,targetId,'mods');if(fs.existsSync(mods))throw new Error('目标模组目录已存在，未覆盖，请重新迁移');await fs.promises.rename(stage,mods);stage='';await fs.promises.writeFile(path.join(plan.folder,'versions',targetId,'migration-report.json'),JSON.stringify(plan,null,2));await fs.promises.rm(marker,{force:true})});plans.delete(id);emit({stage:'done',progress:1,overall:1,text:'版本迁移完成：'+targetId});return {versionId:targetId,folder:plan.folder}
 }finally{running.delete(id);if(stage){const resolved=path.resolve(stage),root=path.resolve(plan.folder)+path.sep;if(!resolved.startsWith(root)||!path.basename(resolved).startsWith('.kamucl-migration-'))throw new Error('迁移临时目录校验失败');await fs.promises.rm(resolved,{recursive:true,force:true})}}
}
