import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import crypto from 'node:crypto'
import { build } from 'esbuild'
import { createRequire } from 'node:module'
const hash=(s:string)=>crypto.createHash('sha1').update(s).digest('hex')
async function harness(){
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'migration-test-')),dir=path.join(root,'versions','source','mods');fs.mkdirSync(dir,{recursive:true});for(const n of ['custom-name.jar','disabled.jar.disabled','unknown.jar'])fs.writeFileSync(path.join(dir,n),n)
 const events:any[]=[],downloads:any[]=[],h:any={root,fail:false,scanned:()=>fs.readdirSync(dir).map(n=>({fileName:n,name:'Internal '+n,version:'old',sha1:hash(fs.readFileSync(path.join(dir,n),'utf8')),fingerprint:1})),files:[{id:'a2',project_id:'a',version_number:'older-compatible',game_versions:['1.20.1'],loaders:['fabric'],version_type:'release',dependencies:[{dependency_type:'required',project_id:'dep'}],files:[{filename:'new-a.jar',url:'https://cdn.modrinth.com/a.jar',hashes:{sha1:hash('new-a')},size:5}]},{id:'b2',project_id:'b',version_number:'new',game_versions:['1.20.1'],loaders:['fabric'],files:[{filename:'new-b.jar',url:'https://cdn.modrinth.com/b.jar',hashes:{sha1:hash('new-b')},size:5}]}]}
 h.post=async(url:string,body:any)=>{const b=JSON.parse(body.body);if(url.endsWith('/fingerprints'))return {ok:true,json:async()=>({data:{exactMatches:[]}})};assert.deepEqual(b.hashes.sort(),h.scanned().map((x:any)=>x.sha1).sort());if(url.endsWith('/update')){assert.deepEqual(b.game_versions,['1.20.1']);assert.deepEqual(b.loaders,['fabric']);return{ok:true,json:async()=>({[hash('custom-name.jar')]:h.files[0],[hash('disabled.jar.disabled')]:h.files[1]})}}return{ok:true,json:async()=>({[hash('custom-name.jar')]:{project_id:'a'},[hash('disabled.jar.disabled')]:{project_id:'b'}})}}
 h.dep={source:'modrinth',projectId:'dep',fileId:'d',fileName:'dep.jar',url:'https://cdn.modrinth.com/dep.jar',sha1:hash('dependency'),gameVersions:['1.20.1'],loaders:['fabric'],dependencies:[],version:'1',size:10,date:'2026',releaseType:'release'}
 h.download=async(url:string,dest:string,_progress:any,sha1:string,_mirror:any,signal?:AbortSignal)=>{signal?.throwIfAborted();downloads.push(url);if(h.fail)throw Error('network failed');const value=url.endsWith('/dep.jar')?'dependency':url.endsWith('/a.jar')?'new-a':'new-b';assert.equal(hash(value),sha1);fs.writeFileSync(dest,value)}
 h.install=async(mc:string,opts:any)=>{events.push(opts);const dest=path.join(root,'versions',opts.instanceName);fs.mkdirSync(dest,{recursive:true});return opts.instanceName}
 const mock:Record<string,string>={modState:'export const isModLocked=()=>false;export const setModLocked=()=>{}',modScan:'export const scanModDirectory=async()=>h.scanned()',resourceDirectory:"export const requireResourceVersion=(s)=>{if(!s||/[\\\\/:]/.test(s))throw Error('id')};export const resolveResourceDirectory=async(folder,id)=>p.join(folder,'versions',id,'mods')",paths:'export const withGameFolder=(folder,fn)=>fn()',versions:'export const installVersion=(...args)=>h.install(...args)',instances:'export const setNewInstanceIsolation=()=>{}',loaders:"export const listLoaderVersions=async()=>['loader-version']",community:'export const communityFiles=async()=>[h.dep];export const communityExactFile=async()=>h.dep;export const cfChannel=()=>({base:"https://cf",key:""})',httpClient:'export const httpFetch=(...args)=>h.post(...args)',download:'export const downloadFile=(...args)=>h.download(...args)'}
 const result=await build({entryPoints:['src/main/core/modMigration.ts'],bundle:true,write:false,platform:'node',format:'cjs',plugins:[{name:'isolate',setup(b){b.onResolve({filter:/^\.\//},a=>{const k=a.path.slice(2);if(mock[k])return{path:k,namespace:'mock'}});b.onLoad({filter:/.*/,namespace:'mock'},a=>({contents:"import p from 'node:path';const h=globalThis.__migrationHarness;"+mock[a.path],loader:'js'}))}}]});(globalThis as any).__migrationHarness=h;const module={exports:{} as any};new Function('require','module','exports',result.outputFiles[0].text)(createRequire(import.meta.url),module,module.exports);return{root,dir,h,events,downloads,api:module.exports,close:()=>{delete(globalThis as any).__migrationHarness;fs.rmSync(root,{recursive:true,force:true})}}
}
test('版本迁移：降级匹配、禁用状态、必要前置、缺失确认、源实例保持完整',async()=>{const t=await harness();try{const before=fs.readdirSync(t.dir).map(n=>[n,fs.readFileSync(path.join(t.dir,n),'utf8')]);const p=await t.api.planModMigration('source',t.root,'1.20.1','fabric');assert.equal(p.entries.length,4);assert.equal(p.entries.find((e:any)=>e.fileName==='unknown.jar').status,'unavailable');await assert.rejects(t.api.applyModMigration(p.id,false,()=>{}),/确认/);const result=await t.api.applyModMigration(p.id,true,()=>{});const dir=path.join(t.root,'versions',result.versionId,'mods');assert.deepEqual(fs.readdirSync(dir).sort(),['dep.jar','new-a.jar','new-b.jar.disabled','unknown.jar.disabled']);assert.equal(fs.readFileSync(path.join(dir,'unknown.jar.disabled'),'utf8'),'unknown.jar');assert.deepEqual(fs.readdirSync(t.dir).map(n=>[n,fs.readFileSync(path.join(t.dir,n),'utf8')]),before);assert(!fs.existsSync(path.join(path.dirname(dir),'.installing')));assert.equal(t.events[0].loader,'fabric')}finally{t.close()}})
test('版本迁移：预览后源文件变化、下载失败和取消都不改原实例',async()=>{const t=await harness();try{let p=await t.api.planModMigration('source',t.root,'1.20.1','fabric');fs.writeFileSync(path.join(t.dir,'custom-name.jar'),'changed');await assert.rejects(t.api.applyModMigration(p.id,true,()=>{}),/变化/);fs.writeFileSync(path.join(t.dir,'custom-name.jar'),'custom-name.jar');p=await t.api.planModMigration('source',t.root,'1.20.1','fabric');t.h.fail=true;await assert.rejects(t.api.applyModMigration(p.id,true,()=>{}),/network failed/);assert.equal(t.events.length,0);assert(!fs.readdirSync(t.root).some(n=>n.startsWith('.kamucl-migration-')));t.h.fail=false;const c=new AbortController();c.abort();await assert.rejects(t.api.applyModMigration(p.id,true,()=>{},c.signal));assert.equal(t.events.length,0)}finally{t.close()}})
test('版本迁移：严格校验目标游戏与加载器、文件哈希、路径和下载协议',async()=>{const t=await harness();try{const f=t.h.dep;assert(t.api.compatibleFile(f,'1.20.1','fabric'));for(const patch of [{loaders:['forge']},{gameVersions:['1.21']},{sha1:''},{fileName:'../x.jar'},{url:'http://unsafe/x.jar'}])assert(!t.api.compatibleFile({...f,...patch},'1.20.1','fabric'))}finally{t.close()}})
test('版本迁移：长名称保持 Forge 安装器64字符限制并避免截断Unicode代理对',async()=>{const t=await harness();try{for(const mc of ['1.21.11','25w14craftmine','26.2']){const name=t.api.migrationInstanceId('测试😀'.repeat(20),mc,'12345678-more');assert(name.length<=64);assert(name.endsWith(mc+' - 12345678'));assert(!/[\uD800-\uDBFF] - /.test(name))}}finally{t.close()}})
