import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import crypto from 'node:crypto'
import { build } from 'esbuild'
import { createRequire } from 'node:module'
import { cleanDesign } from '../src/shared/visualDesign'
import { versionCategory, filterVersions } from '../src/shared/versionPicker'
const hash=(s:string)=>crypto.createHash('sha1').update(s).digest('hex')
async function harness(entry='src/main/core/modManagement.ts'){
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'kamucl-1054-')),dir=path.join(root,'versions','source','mods');fs.mkdirSync(dir,{recursive:true})
 const h:any={root,dir,downloads:[],fail:false,running:false,settings:{theme:'transparent',visualDesign:{version:1,pages:{}},memoryMB:4096},scanned:()=>fs.readdirSync(dir).filter(n=>/\.jar(?:\.disabled)?$/.test(n)).map(n=>({fileName:n,name:'Name '+n,version:'1.0',sha1:hash(fs.readFileSync(path.join(dir,n),'utf8')),fingerprint:1})),files:[]}
 h.files=[{source:'modrinth',projectId:'a',fileId:'new',fileName:'new.jar',url:'https://cdn.modrinth.com/new.jar',sha1:hash('new'),gameVersions:['1.21.1'],loaders:['fabric'],version:'2',date:'2026-09-11',dependencies:[],size:3}]
 h.download=async(url:string,dest:string,_p:any,sha:string)=>{h.downloads.push(url);if(h.fail)throw Error('download failed');if(h.onDownload)await h.onDownload();assert.equal(sha,hash('new'));fs.writeFileSync(dest,'new')}
 h.post=async(url:string)=>({ok:true,json:async()=>url.endsWith('version_files')?Object.fromEntries(h.scanned().map((m:any)=>[m.sha1,{project_id:'a'}])):url.endsWith('fingerprints')?{data:{exactMatches:[]}}:{changelog:'Changes'}})
 const mocks:Record<string,string>={electron:`export const app={getPath:()=>h.root}`,download:'export const downloadFile=(...a)=>h.download(...a);export const downloadAll=async(tasks)=>{await Promise.all(tasks.map(t=>h.download(t.url,t.dest,undefined,t.sha1)))}',modScan:'export const scanModDirectory=async()=>h.scanned()',resourceDirectory:"export const resolveResourceDirectory=async(folder,id)=>p.join(folder,'versions',id,'mods')",paths:'export const withGameFolder=(folder,f)=>f();export const gameDir=()=>h.root',versions:"export const listAllInstalled=()=>[{id:'source',folder:h.root}];export const readVersionJson=()=>({id:'source'})",instanceMetadata:"export const resolveInstanceMetadata=()=>({mcVersion:'1.21.1',loader:'fabric'})",launch:"export const getRunningVersionIds=()=>new Set(h.running?['source']:[])",httpClient:'export const httpFetch=(...a)=>h.post(...a)',community:"export const communityFiles=async()=>h.files;export const communityExactFile=async()=>h.dependency;export const cfChannel=()=>({base:'https://cf',key:''})",settings:"export const getSettings=()=>h.settings;export const saveSettings=(s)=>{if(h.fail)throw Error('disk failed');return h.settings={...h.settings,...s}}"}
 const result=await build({stdin:{contents:`export * from '${path.resolve(entry).replaceAll('\\','/')}';export * from '${path.resolve('src/main/core/modState.ts').replaceAll('\\','/')}';export * from '${path.resolve('src/main/core/modTransaction.ts').replaceAll('\\','/')}';`,resolveDir:process.cwd()},bundle:true,write:false,platform:'node',format:'cjs',plugins:[{name:'isolate',setup(b){b.onResolve({filter:/^(\.\/|electron$)/},a=>{const k=a.path.replace('./','');if(mocks[k])return{path:k,namespace:'mock'}});b.onLoad({filter:/.*/,namespace:'mock'},a=>({contents:"import p from 'node:path';const h=globalThis.__test1054;"+mocks[a.path],loader:'js'}))}}]});(globalThis as any).__test1054=h;const m={exports:{} as any};new Function('require','module','exports',result.outputFiles[0].text)(createRequire(import.meta.url),m,m.exports)
 const write=(name:string,value=name)=>fs.writeFileSync(path.join(dir,name),value)
 return {h,root,dir,api:m.exports,write,read:(name:string)=>fs.readFileSync(path.join(dir,name),'utf8'),close:()=>{delete(globalThis as any).__test1054;assert(path.resolve(root).startsWith(path.resolve(os.tmpdir())+path.sep));fs.rmSync(root,{recursive:true,force:true})}}
}
test('1054 layout data preserves legacy offsets as free mode and bounds layers, locking, spacing',()=>{const d=cleanDesign({version:1,pages:{home:{components:{a:{x:12.5,locked:true,layer:500,padding:24,gap:12},b:{mode:'flow',order:2}}}}});assert.equal(d.pages.home.components.a.mode,'free');assert.equal(d.pages.home.components.a.layer,99);assert.equal(d.pages.home.components.a.locked,true);assert.equal(d.pages.home.components.b.mode,'flow');assert.deepEqual(cleanDesign(JSON.parse(JSON.stringify(d))),d)})
test('1054 complete MC metadata filtering distinguishes releases, RCs, prereleases, snapshots and ancient versions',()=>{const v:any[]=[{id:'1.21.1',type:'release',releaseTime:'2024-08-01'},{id:'26.3-rc-1',type:'snapshot',releaseTime:'2026-09-10'},{id:'1.21 Pre-Release 2',type:'snapshot',releaseTime:'2024-07-01'},{id:'26.3-snapshot-7',type:'snapshot',releaseTime:'2026-09-01'},{id:'b1.7.3',type:'old_beta',releaseTime:'2011-01-01'}];assert.deepEqual(v.map(versionCategory),['release','preview','preview','snapshot','old']);assert.equal(filterVersions(v,'preview','').length,2);assert.equal(filterVersions(v,'all','26.3')[0].id,'26.3-rc-1');assert.equal(filterVersions(v,'release','1.21')[0],v[0]);assert.equal(v[0].id,'1.21.1')})
test('1054 lock persistence uses actual directory and hash/project identity, survives rename and clears aliases on unlock',async()=>{const t=await harness();try{t.write('a.jar','old');const a=hash('old'),b=hash('new');t.api.setModLocked(t.dir,a,true);assert(t.api.isModLocked(t.dir,a));t.api.rememberModIdentity(t.dir,a,'modrinth:a');t.api.transferModLock(t.dir,a,b);assert(t.api.isModLocked(t.dir,b));t.api.setModLocked(t.dir,b,false);assert(!t.api.isModLocked(t.dir,a));assert(!t.api.isModLocked(path.join(t.root,'other'),a));fs.renameSync(path.join(t.dir,'a.jar'),path.join(t.dir,'renamed.jar'));t.api.setModLocked(t.dir,a,true);assert((await t.api.modCatalog('source',t.root))[0].locked);const raw=fs.readdirSync(path.join(t.root,'mod-state'));assert(raw.length===1)}finally{t.close()}})
test('1054 batch enabled target state is idempotent and reports partial failures without overwriting collisions',async()=>{const t=await harness();try{t.write('a.jar');t.write('b.jar');t.write('b.jar.disabled','other');let r=await t.api.setModsEnabled('source',t.root,['a.jar','b.jar','../x.jar'],false);assert.deepEqual(r.map((i:any)=>i.ok),[true,false,false]);assert.equal(t.read('b.jar'),'b.jar');assert.equal(t.read('b.jar.disabled'),'other');r=await t.api.setModsEnabled('source',t.root,['a.jar'],false);assert(r[0].ok);assert.equal(r[0].name,'a.jar.disabled');t.h.running=true;await assert.rejects(t.api.setModsEnabled('source',t.root,['a.jar.disabled'],true),/正在运行/)}finally{t.close()}})
test('1054 offline hash-based locking reports missing files individually',async()=>{const t=await harness();try{t.write('a.jar');t.h.post=()=>{throw Error('offline')};const r=await t.api.lockMods('source',t.root,['a.jar','missing.jar'],true);assert.deepEqual(r.map((i:any)=>i.ok),[true,false]);assert(t.api.isModLocked(t.dir,hash('a.jar')))}finally{t.close()}})
test('1054 replacement preserves original on network, target conflict and source mutation',async()=>{const t=await harness();try{t.write('old.jar','old');const i={oldName:'old.jar',oldSha1:hash('old'),name:'new.jar',sha1:hash('new'),url:'https://cdn/new.jar'};t.h.fail=true;await assert.rejects(t.api.replaceModFiles(t.dir,[i]),/download failed/);assert.equal(t.read('old.jar'),'old');t.h.fail=false;t.write('new.jar','conflict');await assert.rejects(t.api.replaceModFiles(t.dir,[i]),/目标文件已存在/);assert.equal(t.read('new.jar'),'conflict');fs.unlinkSync(path.join(t.dir,'new.jar'));t.h.onDownload=()=>t.write('old.jar','outside');await assert.rejects(t.api.replaceModFiles(t.dir,[i]),/变化/);assert.equal(t.read('old.jar'),'outside')}finally{t.close()}})
test('1054 mid-commit failure rolls original files back',async()=>{const t=await harness();const copy=fs.promises.copyFile;try{t.write('old.jar','old');t.write('second.jar','old');(fs.promises as any).copyFile=async(src:string,dst:string,flags:number)=>{if(dst===path.join(t.dir,'second-new.jar'))throw Error('disk full');return copy(src,dst,flags)};await assert.rejects(t.api.replaceModFiles(t.dir,[{oldName:'old.jar',oldSha1:hash('old'),name:'new.jar',sha1:hash('new'),url:'https://cdn/new.jar'},{oldName:'second.jar',oldSha1:hash('old'),name:'second-new.jar',sha1:hash('new'),url:'https://cdn/new.jar'}]),/disk full/);assert.equal(t.read('old.jar'),'old');assert.equal(t.read('second.jar'),'old');assert(!fs.existsSync(path.join(t.dir,'new.jar')))}finally{fs.promises.copyFile=copy;t.close()}})
test('1054 unsafe mod paths and missing hashes cannot reach downloading',async()=>{const t=await harness();try{for(const name of ['../a.jar','a/b.jar','a:b.jar','a.txt'])assert.throws(()=>t.api.safeModName(name));await assert.rejects(t.api.replaceModFiles(t.dir,[{name:'a.jar',sha1:'',url:'https://cdn/a.jar'}]),/可信哈希/);assert.equal(t.h.downloads.length,0)}finally{t.close()}})
test('1054 single version choices reject unrelated MC/loader and forged choices, preserve disabled and locked state',async()=>{const t=await harness();try{t.write('alias.jar.disabled','old');t.api.setModLocked(t.dir,hash('old'),true);t.h.files.push({...t.h.files[0],fileId:'wrong',loaders:['forge']});const c=await t.api.modVersionChoices('source',t.root,'alias.jar.disabled');assert.equal(c.files.length,1);await assert.rejects(t.api.planModVersionChange(c.id,'forged'),/适配/);const p=await t.api.planModVersionChange(c.id,'new');assert(p.warnings.length);await assert.rejects(t.api.applyModVersionChange(p.id,false),/确认/);await t.api.applyModVersionChange(p.id,true);assert.equal(t.read('new.jar.disabled'),'new');assert(!fs.existsSync(path.join(t.dir,'alias.jar.disabled')));assert(t.api.isModLocked(t.dir,hash('new')))}finally{t.close()}})
test('1054 single version dependency failures require confirmation and source changed after planning is rejected',async()=>{const t=await harness();try{t.write('old.jar','old');t.h.files[0].dependencies=[{required:true,projectId:'missing',fileId:'dep'}];const c=await t.api.modVersionChoices('source',t.root,'old.jar'),p=await t.api.planModVersionChange(c.id,'new');assert(p.warnings.some((w:string)=>w.includes('必要前置')));t.write('extra.jar');await assert.rejects(t.api.applyModVersionChange(p.id,true),/列表发生变化/);assert.equal(t.read('old.jar'),'old')}finally{t.close()}})
test('1054 draft saves do not commit, failed apply retains draft, and unrelated settings survive successful apply',async()=>{const t=await harness('src/main/core/appearanceDraft.ts');try{t.api.saveAppearanceDraft({theme:'blue-white',memoryMB:128});assert.equal(t.h.settings.theme,'transparent');assert.equal(t.api.readAppearanceDraft().theme,'blue-white');t.h.fail=true;assert.throws(()=>t.api.applyAppearanceDraft({theme:'blue-white'}),/disk failed/);assert(t.api.readAppearanceDraft());t.h.fail=false;t.h.settings.memoryMB=8192;t.api.applyAppearanceDraft({theme:'blue-white',memoryMB:128});assert.equal(t.h.settings.memoryMB,8192);assert.equal(t.api.readAppearanceDraft(),null);t.api.saveAppearanceDraft({theme:'orange-black'});t.api.discardAppearanceDraft();assert.equal(t.h.settings.theme,'blue-white')}finally{t.close()}})

test('1058 dependency repair requires an exact installed hash and never replaces its parent or lock',async()=>{
 const t=await harness();try{t.write('parent.jar','old');t.api.setModLocked(t.dir,hash('old'),true);await assert.rejects(t.api.planMissingDependencies('source',t.root,'parent.jar'),/完全一致/);t.h.dependency={...t.h.files[0],projectId:'dep',fileId:'dep',fileName:'dependency.jar'};t.h.files[0]={...t.h.files[0],fileId:'old',fileName:'parent.jar',sha1:hash('old'),dependencies:[{required:true,projectId:'dep',fileId:'dep'}]};const p=await t.api.planMissingDependencies('source',t.root,'parent.jar');assert.deepEqual(p.files.map((f:any)=>f.fileName),['dependency.jar']);await assert.rejects(t.api.applyMissingDependencies(p.id,false),/确认/);await assert.rejects(t.api.applyModVersionChange(p.id,true),/过期/);await t.api.applyMissingDependencies(p.id,true);assert.equal(t.read('parent.jar'),'old');assert.equal(t.read('dependency.jar'),'new');assert(t.api.isModLocked(t.dir,hash('old')))}finally{t.close()}
})
