<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import { IPC, type InstalledVersion, type LoaderName } from '@shared/types'
import type { ModMigrationPlan } from '@shared/modMigration'
import { getManifest, getModIcons, errText } from '../api'
import { store, toast } from '../store'
const props=defineProps<{source:InstalledVersion}>(),emit=defineEmits<{(e:'close'):void}>()
const mc=ref(''),loader=ref<LoaderName>(props.source.loader||'fabric'),versions=ref<string[]>([]),plan=ref<ModMigrationPlan>(),checking=ref(false),starting=ref(false),error=ref(''),confirmed=ref(false),icons=ref<Record<string,string>>({})
const folder=props.source.folder||store.settings!.activeFolder||store.settings!.gameDir
const unavailable=computed(()=>plan.value?.entries.filter(e=>e.status==='unavailable')||[])
const attention=computed(()=>unavailable.value.length+(plan.value?.warnings.length||0)),query=ref(''),onlyMissing=ref(false)
const rows=computed(()=>plan.value?.entries.filter(e=>(!onlyMissing.value||e.status==='unavailable')&&(e.fileName+e.name).toLowerCase().includes(query.value.toLowerCase()))||[])
let generation=0
watch([mc,loader],()=>{generation++;plan.value=undefined;confirmed.value=false;error.value=''})
onUnmounted(()=>generation++)
onMounted(async()=>{try{versions.value=(await getManifest()).map(v=>v.id)}catch{error.value='版本列表加载失败，仍可手动输入游戏版本号'}})
async function inspect(){if(checking.value)return;const current=++generation;checking.value=true;error.value='';confirmed.value=false;try{const result=await window.kamucl.invoke(IPC.modsMigrationPlan,props.source.id,folder,mc.value.trim(),loader.value) as ModMigrationPlan;if(current!==generation)return;plan.value=result;icons.value={};const names=result.entries.filter(e=>e.fileName).map(e=>e.fileName);for(let i=0;i<names.length;i+=100)void getModIcons(props.source.id,names.slice(i,i+100),folder).then(v=>{if(current===generation)icons.value={...icons.value,...v}}).catch(()=>{})}catch(e){if(current===generation)error.value=errText(e)}finally{checking.value=false}}
async function start(){if(!plan.value||starting.value||(attention.value&&!confirmed.value))return;starting.value=true;try{await window.kamucl.invoke(IPC.modsMigrationApply,plan.value.id,confirmed.value);toast('版本迁移已开始，可在下载中心查看进度或取消','success');emit('close')}catch(e){error.value=errText(e)}finally{starting.value=false}}
</script>
<template>
<Teleport to="body"><div class="modal-mask" @pointerdown.self="!starting && emit('close')"><section class="modal migration-modal" role="dialog" aria-modal="true" aria-labelledby="migration-title">
<header><div><h2 id="migration-title">版本迁移</h2><p class="muted">将当前模组迁移到新的隔离实例，原版本保持完整。</p></div><button class="btn btn-ghost" aria-label="关闭版本迁移" :disabled="starting" @click="emit('close')">×</button></header>
<div class="migration-body">
<div class="migration-route"><div><small class="muted">当前版本</small><strong>{{source.name||source.id}}</strong><span class="muted">{{source.mcVersion}} · {{source.loader}}</span></div><span aria-hidden="true">→</span><div><label>目标 Minecraft 版本<input v-model="mc" class="input" list="migration-versions" placeholder="例如 1.21.11，可升级或降级" :disabled="checking||starting"/></label><datalist id="migration-versions"><option v-for="v in versions" :value="v"/></datalist><label>加载器<select v-model="loader" class="input" :disabled="checking||starting"><option value="fabric">Fabric</option><option value="forge">Forge</option><option value="neoforge">NeoForge</option><option value="quilt">Quilt</option></select></label></div></div>
<p class="migration-hint">迁移模组及必要前置，保留启停状态。新实例自动安装游戏与加载器；存档、资源包和配置文件仍保留在原实例。</p>
<div v-if="error" class="migration-error" role="alert">{{error}}</div><div v-if="checking" class="migration-loading"><span class="spin"/> 正在检查每个模组的适配版本与前置依赖…</div>
<template v-if="plan"><div class="migration-summary"><strong>检查完成</strong><span>{{plan.entries.filter(e=>e.status==='compatible').length}} 个可迁移</span><span>{{plan.entries.filter(e=>e.status==='dependency').length}} 个新增前置</span><button class="btn btn-ghost btn-sm" @click="onlyMissing=!onlyMissing">{{unavailable.length}} 个未匹配{{onlyMissing?' · 显示全部':''}}</button></div><input v-model="query" class="input" placeholder="搜索本地文件名或模组名称"/>
<div class="migration-list"><article v-for="(e,index) in rows" :key="e.fileName||e.target?.fileId||index" :class="{unavailable:e.status==='unavailable'}"><img v-if="icons[e.fileName]" :src="icons[e.fileName]" alt=""/><span v-else class="migration-icon">◇</span><div class="migration-mod"><strong :title="e.fileName||e.name">{{e.fileName||e.name}}</strong><small class="muted">{{e.name}}<template v-if="e.disabled"> · 已禁用</template></small><small v-if="e.target">{{e.currentVersion||'新增前置'}} → {{e.target.version}}<span class="muted"> · {{e.target.fileName}}</span></small><small v-else class="migration-error-text">{{e.reason}}</small></div><span class="tag">{{e.status==='unavailable'?'禁用保留':e.status==='dependency'?'新增前置':'可迁移'}}</span></article></div>
<div v-if="attention" class="migration-warning"><strong>以下情况需要你确认</strong><p v-if="unavailable.length">{{unavailable.length}} 个模组没有匹配的适配文件，会复制到新实例并保持禁用，不会丢失原文件。</p><p v-for="warning in plan.warnings">{{warning}}</p><label><input v-model="confirmed" type="checkbox"/>我已了解这些情况，确认继续迁移</label></div>
</template></div>
<footer><span class="muted">下载完成并校验后生成目标实例</span><button class="btn btn-ghost" :disabled="starting" @click="emit('close')">取消</button><button v-if="!plan" class="btn btn-gold" :disabled="!mc.trim()||checking" @click="inspect">{{checking?'检查中…':'检查兼容性'}}</button><template v-else><button class="btn btn-ghost" :disabled="starting" @click="inspect">重新检查</button><button class="btn btn-gold" :disabled="starting||(attention>0&&!confirmed)" @click="start">{{starting?'正在创建任务…':'确认迁移'}}</button></template></footer>
</section></div></Teleport>
</template>
<style scoped>
.migration-modal{width:min(880px,calc(100vw - 40px));max-height:calc(100vh - 60px);padding:0;display:flex;flex-direction:column;overflow:hidden}.migration-modal header,.migration-modal footer{display:flex;align-items:center;gap:12px;padding:20px 24px;flex-shrink:0}.migration-modal header{justify-content:space-between;border-bottom:1px solid var(--border)}.migration-modal h2{margin:0;font-size:22px}.migration-modal p{margin:6px 0;line-height:1.65}.migration-body{padding:20px 24px;overflow:auto;min-height:0}.migration-route{display:grid;grid-template-columns:1fr 30px 1fr;gap:18px;align-items:center;background:var(--card-2);border-radius:14px;padding:18px}.migration-route>div{display:flex;flex-direction:column;gap:8px;min-width:0}.migration-route strong{overflow-wrap:anywhere}.migration-route label{display:flex;flex-direction:column;gap:5px}.migration-route .input{width:100%}.migration-hint{font-size:13px;color:var(--text-dim);padding:10px 0}.migration-summary{display:flex;align-items:center;gap:12px;flex-wrap:wrap;padding:12px 0}.migration-list article{display:flex;gap:12px;align-items:center;padding:12px 0;border-bottom:1px solid var(--border)}.migration-list img,.migration-icon{width:36px;height:36px;object-fit:contain;border-radius:8px;flex-shrink:0}.migration-mod{display:flex;flex-direction:column;gap:4px;min-width:0;flex:1}.migration-mod strong{font-size:14px;overflow-wrap:anywhere}.migration-mod small{font-size:12px;overflow-wrap:anywhere}.migration-warning{margin-top:16px;padding:16px;background:color-mix(in srgb,var(--accent) 9%,var(--card));border:1px solid var(--border-strong);border-radius:12px}.migration-warning label{display:flex;gap:8px;align-items:center;margin-top:10px}.migration-error,.migration-error-text{color:var(--danger,#e75b65)}.migration-error{padding:10px 0}.migration-loading{display:flex;align-items:center;gap:10px;padding:20px 0}.migration-modal footer{border-top:1px solid var(--border);justify-content:flex-end}.migration-modal footer>span{margin-right:auto;font-size:12px}@media(max-width:650px){.migration-route{grid-template-columns:1fr}.migration-modal footer{flex-wrap:wrap}.migration-modal footer>span{width:100%}}
</style>
