<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue'
import type { InstalledVersion } from '@shared/types'
import type { ModVersionChoices, ModChangePlan } from '@shared/modManagement'
import { errText } from '../api'
const props=defineProps<{source:InstalledVersion;fileName:string}>(),emit=defineEmits<{(e:'close'):void;(e:'done'):void}>()
const choices=ref<ModVersionChoices>(),plan=ref<ModChangePlan>(),loading=ref(true),checking=ref(false),applying=ref(false),error=ref(''),selected=ref(''),confirmed=ref(false)
let generation=0
onUnmounted(()=>generation++)
async function load(){loading.value=true;error.value='';try{choices.value=await window.kamucl.invoke('mods:versionChoices',props.source.id,props.source.folder,props.fileName) as ModVersionChoices}catch(e){error.value=errText(e)}finally{loading.value=false}}
async function select(fileId:string){const g=++generation;selected.value=fileId;plan.value=undefined;checking.value=true;confirmed.value=false;error.value='';try{const p=await window.kamucl.invoke('mods:versionPlan',choices.value!.id,fileId) as ModChangePlan;if(g===generation)plan.value=p}catch(e){if(g===generation)error.value=errText(e)}finally{if(g===generation)checking.value=false}}
async function apply(){if(!plan.value)return;applying.value=true;try{await window.kamucl.invoke('mods:versionApply',plan.value.id,confirmed.value);emit('done');emit('close')}catch(e){error.value=errText(e)}finally{applying.value=false}}
onMounted(load)
</script>
<template><Teleport to="body"><div class="modal-mask" @pointerdown.self="!applying&&emit('close')"><section class="modal mod-version-modal" role="dialog" aria-modal="true" aria-label="切换模组版本"><header><div><h2>切换模组版本</h2><p class="muted">{{fileName}}</p><small v-if="choices" class="muted">{{choices.mcVersion}} · {{choices.loader}} · 当前 {{choices.currentVersion}}</small></div><button class="btn btn-ghost" :disabled="applying" aria-label="关闭" @click="emit('close')">×</button></header><div class="version-content"><div v-if="loading" class="empty">正在识别来源并查询适配版本…</div><div v-if="error" class="error">{{error}}<button v-if="!choices" class="btn btn-ghost" @click="load">重试</button></div><template v-if="choices"><div class="version-columns"><div class="versions-list"><button v-for="f in choices.files" :key="f.fileId" :class="{active:selected===f.fileId}" :disabled="applying" @click="select(f.fileId)"><strong>{{f.version}}</strong><small>{{f.releaseType}} · {{f.date?.slice(0,10)}}</small><small>{{f.fileName}}</small></button><p v-if="!choices.files.length">此游戏版本与加载器下没有其他可下载文件。</p></div><div class="version-detail"><p v-if="checking" class="muted">正在检查前置并获取版本说明…</p><template v-else-if="plan"><h3>本次更改</h3><p v-for="f in plan.files"><span class="tag">{{f.dependency?'新增前置':'替换模组'}}</span> {{f.fileName}}</p><div v-if="plan.warnings.length" class="warning"><p v-for="w in plan.warnings">{{w}}</p><label><input v-model="confirmed" type="checkbox">我已了解并确认本次更改</label></div><h3>版本说明</h3><pre>{{plan.changelog}}</pre></template><p v-else class="muted">选择一个适配版本，查看说明与必要前置。</p></div></div></template></div><footer><small class="muted">校验后替换，保留启停状态</small><button class="btn btn-ghost" :disabled="applying" @click="emit('close')">取消</button><button class="btn btn-gold" :disabled="!plan||checking||applying||(!!plan?.warnings.length&&!confirmed)" @click="apply">{{applying?'正在下载与替换…':'确认切换'}}</button></footer></section></div></Teleport></template>
<style scoped>
.mod-version-modal{width:min(920px,calc(100vw - 48px));max-height:calc(100vh - 64px);padding:0;display:flex;flex-direction:column;overflow:hidden}.mod-version-modal header,.mod-version-modal footer{display:flex;gap:12px;align-items:center;padding:20px 24px;flex-shrink:0}.mod-version-modal header{justify-content:space-between;border-bottom:1px solid var(--border)}h2{margin:0;font-size:21px}.mod-version-modal header p{margin:7px 0;overflow-wrap:anywhere}.version-content{min-height:0;overflow:auto;padding:20px 24px}.version-columns{display:grid;grid-template-columns:300px minmax(0,1fr);gap:24px}.versions-list{max-height:430px;overflow:auto;overscroll-behavior:contain}.versions-list button{display:flex;flex-direction:column;width:100%;text-align:left;padding:12px;border:1px solid var(--border);border-radius:10px;margin-bottom:8px;gap:4px;background:var(--card-2);color:var(--text);cursor:pointer;overflow-wrap:anywhere}.versions-list button.active{background:var(--accent-soft);border-color:var(--accent)}.versions-list small{color:var(--text-dim);font-size:11px}.version-detail{min-width:0}.version-detail pre{white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.8 inherit}.version-detail h3{font-size:14px}.version-detail p{font-size:12px;overflow-wrap:anywhere}.warning{background:var(--accent-soft);border-radius:10px;padding:12px}.error{color:var(--danger);padding-bottom:15px}.mod-version-modal footer{border-top:1px solid var(--border);justify-content:flex-end}.mod-version-modal footer small{margin-right:auto}@media(max-width:700px){.version-columns{grid-template-columns:1fr}.versions-list{max-height:220px}}
</style>
